### ISSUE TITLE
CI test failure

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/feisty#29]
The `build-docs` test [failed](https://github.com/marbl-ecosys/feisty/runs/5223968427?check_suite_focus=true) on #25 despite passing earlier and no changes that should have affected this particular test. The error message points to missing `black` in the environment:

```
Exception occurred:
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'black' distribution was not found and is required by the application
The full traceback has been saved in /tmp/sphinx-err-5ghsjkqs.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

looking at the `conda` environment being set up, I don't really understand why it was omitted... here are differences from the conda output (`<` is output from the [passing test](https://github.com/marbl-ecosys/feisty/runs/5209357189?check_suite_focus=true), `>` is from the failing test linked previously):

```diff
<   + appdirs                               1.4.4  pyh9f0ad1d_0            conda-forge/noarch         13kB
<   + black                                21.5b2  pyhd8ed1ab_0            conda-forge/noarch        111kB
<   + filelock                              3.5.0  pyhd8ed1ab_0            conda-forge/noarch         12kB
---
>   + filelock                              3.5.1  pyhd8ed1ab_0            conda-forge/noarch         12kB
<   + ipykernel                             6.9.0  py38he5a9106_0          conda-forge/linux-64      186kB
<   + ipython                               8.0.1  py38h578d9bd_0          conda-forge/linux-64        1MB
---
>   + ipykernel                             6.9.1  py38he5a9106_0          conda-forge/linux-64      186kB
>   + ipython                               8.0.1  py38h578d9bd_1          conda-forge/linux-64        1MB
<   + jupyter_core                          4.9.1  py38h578d9bd_1          conda-forge/linux-64       82kB
---
>   + jupyter_core                          4.9.2  py38h578d9bd_0          conda-forge/linux-64       82kB
<   + mypy_extensions                       0.4.3  py38h578d9bd_4          conda-forge/linux-64       11kB
<   + pathspec                              0.9.0  pyhd8ed1ab_0            conda-forge/noarch         31kB
<   + regex                             2022.1.18  py38h497a2fe_0          conda-forge/linux-64      383kB
<   + typed-ast                             1.5.2  py38h497a2fe_0          conda-forge/linux-64      218kB
```

So `filelock`, `ipykernel`, and `jupyter_core` all incremented the patch version number and there's a change in the hash of `ipython` despite remaining at 8.0.1; but now `appdirs`, `black`, `mypy_extensions`, `pathspec`, `regex`, and `typed-ast` are all missing.

I'll rerun the test and see if the problem is reproducible. If it is, we may just need to add some (or all) of the above packages to `ci/environment.yml`

****

Appendix A: Full traceback

```
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/jupyter_book/sphinx.py", line 167, in build_sphinx
    app.build(force_all, filenames)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 534, in write
    self._write_serial(sorted(docnames))
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 544, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 605, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/writers/html.py", line 71, in translate
    self.document.walkabout(visitor)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 1 more time]
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/util/docutils.py", line 468, in dispatch_visit
    method(node)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/writers/html5.py", line 405, in visit_literal_block
    highlighted = self.highlighter.highlight_block(
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/highlighting.py", line 133, in highlight_block
    lexer = self.get_lexer(source, lang, opts, force, location)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/sphinx/highlighting.py", line 117, in get_lexer
    lexer = get_lexer_by_name(lang, **opts)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/pygments/lexers/__init__.py", line 115, in get_lexer_by_name
    for cls in find_plugin_lexers():
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/pygments/plugin.py", line 54, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2464, in load
    self.require(*args, **kwargs)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2487, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'black' distribution was not found and is required by the application

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/dev-feisty/bin/jupyter-book", line 10, in <module>
    sys.exit(main())
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/jupyter_book/cli/main.py", line 323, in build
    builder_specific_actions(
  File "/usr/share/miniconda/envs/dev-feisty/lib/python3.8/site-packages/jupyter_book/cli/main.py", line 535, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError: 
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================
```

**Comment by mnlevy1981** [comment]
The test passed when I [reran](https://github.com/marbl-ecosys/feisty/runs/5238078665?check_suite_focus=true) it. Weird.
